spring:
  application:
    name: ot-zero-gen-ai
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ot_zero_gen_ai
    username: root
    password: 4869
  profiles:
    active: local
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packagesToScan: com.oceantaker.otzerogenai.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

